// Eval harness: `npx tsx bench/run.ts` runs every mode/era/preset combo that matters on the synthetic samples,
// records validator pass, colour count vs limit, time and look-lock consistency, and writes bench/RESULTS.md.
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { animate } from "../src/pixel/effects";
import { pixelize } from "../src/pixel/pipeline";
import { pixelizeSprite } from "../src/pixel/sprite";
import { pixelizeTile } from "../src/pixel/tile";
import { ERAS, type Era, type Look, type PixelOptions, type PixelResult, type Preset } from "../src/pixel/types";
import { validate } from "../src/pixel/validate";
import { samples, type Sample } from "./samples";

export interface Row { sample: string; mode: string; era: number; preset: string; extra: string; ok: boolean; colours: number; limit: number; ms: number; issues: string[] }
export interface LockRow { era: number; preset: string; identical: boolean }

const run = (s: Sample, o: PixelOptions): PixelResult =>
  s.mode === "tile" ? pixelizeTile(s.img, o) : s.mode === "sprite" ? pixelizeSprite(s.img, o) : pixelize(s.img, o);

export function bench(opts: { full: boolean }) {
  const all = samples();
  const eras: Era[] = opts.full ? [8, 16, 32, 64] : [8, 32];
  const presets: Preset[] = opts.full ? ["vivid", "neon", "pastel", "warm", "cool", "sepia", "neutral"] : ["vivid", "neon"];
  const rows: Row[] = [];
  const measure = (s: Sample, era: Era, preset: Preset, extra: Partial<PixelOptions>, label: string) => {
    const width = s.mode === "scene" ? (opts.full ? ERAS[era].width : Math.min(ERAS[era].width, 160)) : 32;
    const t = performance.now();
    const r = run(s, { era, preset, width, seed: 1, ...extra });
    const ms = Math.round(performance.now() - t);
    const v = validate(r.native, { maxColours: ERAS[era].colours });
    rows.push({ sample: s.name, mode: s.mode, era, preset, extra: label, ok: v.ok, colours: v.colours, limit: ERAS[era].colours, ms, issues: v.issues });
  };
  for (const s of all) for (const era of eras) {
    for (const p of presets) measure(s, era, p, {}, "-");
    if (s.mode === "scene") {
      measure(s, era, "vivid", { bloom: "med", dither: "low", outline: true }, "bloom=med dither=low outline");
      measure(s, era, "vivid", { dither: "med" }, "dither=med");
    }
    if (s.mode === "sprite") measure(s, era, "vivid", { outline: true }, "outline");
  }
  // look lock: the palette saved from image A must be the exact palette of image A and of a different image B.
  const lock: LockRow[] = [];
  const [A, B] = [all[0], all[2]];
  for (const era of eras) for (const preset of presets.slice(0, 2)) {
    const a = pixelize(A.img, { era, preset, width: 160 });
    const look: Look = { id: "bench", name: "bench", era, palette: a.palette, preset, bloom: "off", dither: "off", outline: false };
    const sorted = (p: string[]) => JSON.stringify([...p].sort());
    const b = pixelize(B.img, { look, width: 160 });
    const c = pixelize(A.img, { look, width: 160 });
    lock.push({ era, preset, identical: sorted(b.palette) === sorted(look.palette) && sorted(c.palette) === sorted(look.palette) });
  }
  const water = all.find((s) => s.name === "water")!;
  const t = performance.now();
  const anim = animate(pixelize(water.img, { era: 16, width: 160 }), ["rain", "shimmer"], { frames: 8, seed: 1 });
  const fx = { frames: anim.frames.length, ms: Math.round(performance.now() - t), ok: anim.frames.every((f) => validate(f).ok) };
  return { rows, lock, fx };
}

export function markdown(r: ReturnType<typeof bench>, full: boolean): string {
  const pass = r.rows.filter((x) => x.ok && x.colours <= x.limit).length;
  return [
    "# Bench results", "",
    `Generated by \`npx tsx bench/run.ts\` (${full ? "full" : "reduced"} matrix) on 8 synthetic images (bench/samples.ts).`, "",
    `- Validator + colour limit: **${pass}/${r.rows.length}** pass`,
    `- Look lock gives the identical palette on different images: **${r.lock.filter((x) => x.identical).length}/${r.lock.length}**`,
    `- Effect loop (rain+shimmer, ${r.fx.frames} frames): ${r.fx.ok ? "all frames valid" : "FAILED"}, ${r.fx.ms} ms`,
    `- Total pixelize time: ${(r.rows.reduce((a, x) => a + x.ms, 0) / 1000).toFixed(1)} s, slowest ${Math.max(...r.rows.map((x) => x.ms))} ms`, "",
    "## Runs", "", "| sample | mode | era | preset | extra | valid | colours/limit | ms |", "|---|---|---|---|---|---|---|---|",
    ...r.rows.map((x) => `| ${x.sample} | ${x.mode} | ${x.era} | ${x.preset} | ${x.extra} | ${x.ok ? "yes" : "NO " + x.issues[0]} | ${x.colours}/${x.limit} | ${x.ms} |`),
    "", "## Look lock", "", "| era | preset | same palette across images |", "|---|---|---|",
    ...r.lock.map((x) => `| ${x.era} | ${x.preset} | ${x.identical ? "yes" : "NO"} |`), "",
  ].join("\n");
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const full = !process.argv.includes("--quick");
  const r = bench({ full });
  const out = join(dirname(fileURLToPath(import.meta.url)), "RESULTS.md");
  writeFileSync(out, markdown(r, full));
  const bad = r.rows.filter((x) => !x.ok || x.colours > x.limit).length + r.lock.filter((x) => !x.identical).length + (r.fx.ok ? 0 : 1);
  console.log(`bench: ${r.rows.length} runs, ${bad} failures -> ${out}`);
  process.exit(bad ? 1 : 0);
}
