// One minimal valid call per tool. Shown at the end of every tool description and in validation errors,
// so a model that gets a field wrong sees exactly what a correct call looks like. Tests parse each one.
export const TOOL_EXAMPLES: Record<string, Record<string, unknown>> = {
  get_style_guide: {},
  list_generators: { category: "environment" },
  generate_asset: { generator: "environment", params: { kind: "oak" }, seed: 42, name: "oak tree" },
  generate_variations: { generator: "environment", count: 6, vary: "params" },
  paint_asset: { name: "gem", category: "object", width: 4, height: 4, frames: [[".aa.", "abba", "abba", ".aa."]] },
  edit_asset: { id: "<asset id or name>", pixels: [{ x: 1, y: 1, char: "a" }] },
  edit_region: { id: "<asset id or name>", rect: { x: 0, y: 0, w: 4, h: 4 }, rows: ["aaaa", "aaaa", "aaaa", "aaaa"] },
  list_assets: { category: "object" },
  get_asset: { id: "<asset id or name>" },
  delete_asset: { id: "<asset id or name>" },
  export_asset: { id: "<asset id or name>", format: "spritesheet", scale: 4 },
  import_image: { path: "./art/tree.png", category: "environment", width: 32, height: 32 },
  list_kits: {},
  create_kit: { name: "Moody", base_kit_id: "<kit id>", changes: { outline: "black" } },
  update_kit: { kit_id: "<kit id>", changes: { outline: "black" } },
  set_active_kit: { kit_id: "<kit id or name>" },
  rerender_assets: { stale_only: true },
  list_rigs: {},
  list_clips: {},
  list_attachments: {},
  generate_rigged: { rig: "humanoid", clips: ["walk", "idle"], directions: 4, name: "hero" },
  attach: { id: "<asset id or name>", add: ["hat"] },
  create_rig: { rig: { id: "crab", name: "Crab", grid: 32, joints: [], parts: [], slots: {} } },
  create_clip: { clip: { id: "wiggle", name: "Wiggle", frames: [] }, rig: "crab" },
  create_attachment: { attachment: { id: "cape", name: "Cape", parts: [] }, rig: "humanoid" },
  generate_pack: { pack: "farming-v1", dry_run: true },
  import_svg: { path: "./art/tree.svg" },
  add_reference: { path: "./refs/house.png", name: "house" },
  list_references: {},
  get_reference: { id: "<reference id or name>" },
  delete_reference: { id: "<reference id or name>" },
  kit_from_reference: { reference_id: "<reference id or name>", name: "From house" },
  compare_to_reference: { asset_id: "<asset id or name>", reference_id: "<reference id or name>" },
};

export function exampleLine(tool: string): string {
  return `${tool} ${JSON.stringify(TOOL_EXAMPLES[tool] ?? {})}`;
}
